// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhhxTAV5R8YyQmTJlgMQ7Hi6tekFMOlg4',
    appId: '1:1076130987429:web:89eea30d33c387e396fc4c',
    messagingSenderId: '1076130987429',
    projectId: 'healthy-mind-c8d8e',
    authDomain: 'healthy-mind-c8d8e.firebaseapp.com',
    storageBucket: 'healthy-mind-c8d8e.firebasestorage.app',
    measurementId: 'G-46RFYNEDYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIjhVUeJokYGURa2fvadAiCBc9jFkbNdg',
    appId: '1:1076130987429:android:da374db67e0f35b596fc4c',
    messagingSenderId: '1076130987429',
    projectId: 'healthy-mind-c8d8e',
    storageBucket: 'healthy-mind-c8d8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP-Zrb0lyvoTCCh7P0RvCOaExpWbtgMnw',
    appId: '1:1076130987429:ios:9d830b39840d227396fc4c',
    messagingSenderId: '1076130987429',
    projectId: 'healthy-mind-c8d8e',
    storageBucket: 'healthy-mind-c8d8e.firebasestorage.app',
    iosClientId: '1076130987429-e8gei2vjtrtm3v1dqocusr6iom43kfkp.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthyMindApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP-Zrb0lyvoTCCh7P0RvCOaExpWbtgMnw',
    appId: '1:1076130987429:ios:9d830b39840d227396fc4c',
    messagingSenderId: '1076130987429',
    projectId: 'healthy-mind-c8d8e',
    storageBucket: 'healthy-mind-c8d8e.firebasestorage.app',
    iosClientId: '1076130987429-e8gei2vjtrtm3v1dqocusr6iom43kfkp.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthyMindApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhhxTAV5R8YyQmTJlgMQ7Hi6tekFMOlg4',
    appId: '1:1076130987429:web:7461de0fb3efb98f96fc4c',
    messagingSenderId: '1076130987429',
    projectId: 'healthy-mind-c8d8e',
    authDomain: 'healthy-mind-c8d8e.firebaseapp.com',
    storageBucket: 'healthy-mind-c8d8e.firebasestorage.app',
    measurementId: 'G-5ZZG4LS8D0',
  );
}
